server:
  port: 8761

spring:
  application:
    name: discovery-service
    
eureka:
  instance:
    hostname: 104.198.148.105
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/